spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: books-service
          uri: lb://books-service
          predicates:
            - Path=/book/**
          filters:
            - StripPrefix=1
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
